packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

variable "aws_access_key" {
  type    = string
  default = "${env("AWS_ACCESS_KEY_ID")}"
}

variable "aws_secret_key" {
  type    = string
  default = "${env("AWS_SECRET_ACCESS_KEY")}"
}

source "amazon-ebs" "autogenerated_1" {
  access_key    = "${var.aws_access_key}"
  ami_name      = "k8s 1.20 debian 12"
  instance_type = "t3a.micro"
  region        = "us-east-2"
  secret_key    = "${var.aws_secret_key}"
  source_ami    = "ami-0ddf7dfd13a83d8c8"
  ssh_username  = "admin"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    script = "base.sh"
  }

}
